## 异步

- 回调的Ioc
- Promise的局限性
	- 顺序错误处理：等同于`try...catch`的问题，一旦捕获了错误就在本地消化了，但是有些错误是全局的致命性错误，就是应该报出去
		- PS：之前看hax直播时有讲过tc39有一个提案就是解决这个问题
		- 顺便最近还有一个有关错误的特性，`Error Cause`可以给出更有意义的错误原因`new Error(message, { cause })`
	- 单一值：只返回一个值，但有时要一次性获取一组值
		- 可以返回对象或数组
		- 可以使用`Promise.all`
	- 单决议：只能完成或拒绝一次，但是还有一种类似事件流的模式
		- 可以使用其他库代替，例如Rx.js
	- 无法取消：如果请求过程中时间过长，程序会卡住，而且还不能手动取消
		- 但是可以使用AbortSignal创建会取消的Promise
- Generator协程
- Async/Await：Promise+Generator
- 异步控制流
	- 顺序执行
	- 并发执行

```js
async function abortable(signal, promise) {
  if (signal.aborted) throw new DOMException('AbortError', 'AbortError');
  let listener;

  return Promise.race([
    new Promise((_, reject) => {
      listener = () => reject(new DOMException('AbortError', 'AbortError'));
      signal.addEventListener('abort', listener);
    }),
    promise,
  ]).finally(() => signal.removeEventListener('abort', listener));
}

// Usage
const controller = new AbortController();
try {
	const result = await abortable(controller.signal, Promise.resolve());
} catch(e) {
	console.warn(e.name === 'AbortError' ? 'Promise Aborted' : 'Promise Rejfected');
}
controller.abort();

// 或者
AbortSignal.prototype.race = async function(promise) {
	if(this.aborted) throw new DOMException('', 'AbortError');
	let obAbort;

	return Promise.race([
		new Promise((_, reject) => {
			onAbort = () => reject(new DOMException('', 'AbortError'));
			this.addEventListener('abort', onAbort);
		}),
		promise
	]).finally(() => this.removeEventListener('abort', onAbort))
}

// Usage
const { signal, abort } = new AbortController();
const res = await fetch(searchURL, { signal });
const { addSearchResults } = await signal.race(import('./search-helpers.js'));
await addSearchResults('response', { signal });
```

## 性能

### 程序性能

- WebWorker：专用于计算CPU密集型任务的多线程编程
- WASM：抛弃JS使用其他高性能语言

### 性能测试与调优

- 使用`benchmark.js`测试性能，用`jsPref.com`进行众包性能测试
- 编写好的测试，从用户用例触发
